<?php

namespace App\Console\Commands;

use App\Models\MediaBrief;
use App\Services\Media\GeneratedMediaImporter;
use App\Services\Media\GenerationMatcher;
use Illuminate\Console\Command;

/**
 * Takes a dump of the Higgsfield account's generation history and files every
 * image against the brief that asked for it.
 *
 * Expected input, one object per generation:
 *   {"generations": [{"id": "...", "prompt": "...", "url": "https://..."}]}
 *
 * That is the shape `show_generations` returns, so a dump can be handed
 * straight over. Nothing here talks to Higgsfield: the history is fetched by
 * whatever can reach the account, and this command does the association and
 * the import.
 */
class SyncWebGenerations extends Command
{
    protected $signature = 'media:sync
        {file : JSON dump of the account generation history}
        {--dry-run : report what would be matched without importing}';

    protected $description = 'File images generated by hand in the web app against their briefs';

    public function handle(GenerationMatcher $matcher, GeneratedMediaImporter $importer): int
    {
        $raw = @file_get_contents($this->argument('file'));

        if ($raw === false) {
            $this->error('Could not read '.$this->argument('file'));

            return self::FAILURE;
        }

        $payload = json_decode($raw, true);
        $generations = $payload['generations'] ?? $payload['items'] ?? null;

        if (! is_array($generations)) {
            $this->error('Expected {"generations": [...]}.');

            return self::FAILURE;
        }

        $outcome = $matcher->match($this->normalise($generations));
        $matched = $outcome['matched'];

        $this->line(sprintf(
            '%d generation(s) read: %d matched a brief, %d could not be placed%s.',
            count($generations),
            count($matched),
            count($outcome['unmatched']),
            $outcome['already'] ? ', '.$outcome['already'].' superseded by a newer take' : '',
        ));

        if ($outcome['unmatched'] !== []) {
            $this->newLine();
            $this->warn('Not placed - their prompts match no brief:');

            foreach (array_slice($outcome['unmatched'], 0, 5) as $item) {
                $this->line('  '.\Illuminate\Support\Str::limit((string) ($item['prompt'] ?? '(no prompt)'), 90));
            }

            if (count($outcome['unmatched']) > 5) {
                $this->line('  ... and '.(count($outcome['unmatched']) - 5).' more');
            }
        }

        if ($matched === []) {
            return self::SUCCESS;
        }

        if ($this->option('dry-run')) {
            $this->newLine();
            $this->table(
                ['brief', 'kind', 'status'],
                collect($matched)->map(function ($_, $id) {
                    $b = MediaBrief::find($id);

                    return [$id, $b?->kind ?? '—', $b?->status ?? 'MISSING'];
                })->values()->all(),
            );
            $this->line('Dry run - nothing imported.');

            return self::SUCCESS;
        }

        $result = $importer->importMany($matched);

        $this->newLine();
        $this->info("imported {$result['imported']}, already present {$result['skipped']}, failed {$result['failed']}");

        foreach ($result['errors'] as $id => $message) {
            $this->warn("  brief {$id}: {$message}");
        }

        $this->line(MediaBrief::renderable()->count().' brief(s) still to render.');

        return $result['failed'] > 0 ? self::FAILURE : self::SUCCESS;
    }

    /**
     * Accept the raw `show_generations` shape as well as a flattened one, so a
     * dump can be pasted through without being reshaped by hand.
     *
     * @return list<array{id:string,prompt:string,url:string}>
     */
    private function normalise(array $generations): array
    {
        $out = [];

        foreach ($generations as $item) {
            $url = $item['url']
                ?? $item['results']['rawUrl']
                ?? $item['results']['url']
                ?? null;

            $prompt = $item['prompt'] ?? $item['params']['prompt'] ?? null;

            if (! $url || ! $prompt) {
                continue;
            }

            $out[] = ['id' => $item['id'] ?? null, 'prompt' => $prompt, 'url' => $url];
        }

        return $out;
    }
}
