<?php

namespace App\Services\Media;

use App\Models\MediaBrief;

/**
 * Matches images generated by hand in the Higgsfield web app back to the
 * briefs that asked for them.
 *
 * The account's unlimited model packs are only reachable from the web app, so
 * the practical way to render this course is for a person to paste prompts
 * there. That leaves the results sitting in the account's history with no link
 * to the lesson they belong to - and 2,500 of them cannot be re-associated by
 * hand. The prompt text is the only thing carried through, so the prompt is the
 * key.
 *
 * Matching has to survive how people actually paste. The observed history
 * contains prompts pasted twice over, with trailing spaces and collapsed
 * newlines, so an exact string comparison finds nothing.
 */
class GenerationMatcher
{
    /**
     * @param  list<array{id:string,prompt:string,url:string,width?:int,height?:int}>  $generations
     * @return array{matched:array<int,array>, unmatched:list<array>, already:int}
     */
    public function match(array $generations): array
    {
        $index = $this->briefIndex();

        $matched = [];
        $unmatched = [];
        $already = 0;

        foreach ($generations as $generation) {
            $key = $this->fingerprint((string) ($generation['prompt'] ?? ''));

            if ($key === '' || ! isset($index[$key])) {
                $unmatched[] = $generation;

                continue;
            }

            $briefId = $index[$key];

            // The history is newest-first and a prompt may have been run more
            // than once. The first match wins, so a retry supersedes the take
            // it replaced rather than fighting with it.
            if (isset($matched[$briefId])) {
                $already++;

                continue;
            }

            $matched[$briefId] = [
                'status' => 'ok',
                'url' => $generation['url'],
                'generation_id' => $generation['id'] ?? null,
            ];
        }

        return ['matched' => $matched, 'unmatched' => $unmatched, 'already' => $already];
    }

    /** @return array<string,int> fingerprint => brief id */
    private function briefIndex(): array
    {
        $index = [];

        MediaBrief::whereNot('status', MediaBrief::STATUS_SKIPPED)
            ->select(['id', 'prompt'])
            ->chunkById(500, function ($briefs) use (&$index) {
                foreach ($briefs as $brief) {
                    $key = $this->fingerprint($brief->prompt);

                    if ($key !== '') {
                        // Two briefs can legitimately share a prompt. Keeping the
                        // lower id makes the mapping deterministic rather than
                        // dependent on chunk order.
                        $index[$key] ??= $brief->id;
                    }
                }
            });

        return $index;
    }

    /**
     * Reduce a prompt to something that survives being pasted by a human.
     *
     * Whitespace is collapsed because newlines vanish in a textarea, and an
     * exactly-doubled prompt is folded back to one copy because pasting twice
     * is the single most common slip - every generation observed so far had it.
     */
    public function fingerprint(string $prompt): string
    {
        $clean = trim(preg_replace('/\s+/u', ' ', $prompt) ?? '');

        if ($clean === '') {
            return '';
        }

        $clean = $this->undouble($clean);

        return hash('sha256', mb_strtolower($clean));
    }

    private function undouble(string $text): string
    {
        $length = mb_strlen($text);

        // Pasted twice with no separator.
        if ($length % 2 === 0) {
            $half = mb_substr($text, 0, intdiv($length, 2));

            if ($half === mb_substr($text, intdiv($length, 2))) {
                return $half;
            }
        }

        // Pasted twice with a space between the copies.
        if ($length % 2 === 1) {
            $half = mb_substr($text, 0, intdiv($length, 2));

            if ($half.' '.$half === $text) {
                return $half;
            }
        }

        return $text;
    }
}
