import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:zaban/features/lesson/data/models/media_ref.dart';

part 'exercise.freezed.dart';
part 'exercise.g.dart';

/// A gradable item.
///
/// [templateCode] is the `exercise_templates.code` the backend seeds
/// (`multiple_choice`, `fill_blank`, `match`, `sentence_reorder`,
/// `error_correction`, …) and is what the renderer switches on.
///
/// Note what is *absent*: no correct answer and no `is_correct` on the options.
/// Grading happens server-side; the client submits a response and renders the
/// [AttemptResult] it gets back.
@freezed
abstract class Exercise with _$Exercise {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory Exercise({
    required int id,
    required String templateCode,
    required String stem,
    String? instructions,
    String? blockType,
    String? skillCode,
    String? cefr,
    double? difficulty,
    @Default(<ExerciseOption>[]) List<ExerciseOption> options,
    @Default(<String, dynamic>{}) Map<String, dynamic> payload,
    MediaRef? image,
    MediaRef? audio,
    ExercisePassage? passage,
    @Default(<String>[]) List<String> hints,
  }) = _Exercise;

  factory Exercise.fromJson(Map<String, dynamic> json) =>
      _$ExerciseFromJson(json);
}

@freezed
abstract class ExerciseOption with _$ExerciseOption {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory ExerciseOption({
    required int id,
    @Default(0) int position,
    String? text,
    MediaRef? media,
  }) = _ExerciseOption;

  factory ExerciseOption.fromJson(Map<String, dynamic> json) =>
      _$ExerciseOptionFromJson(json);
}

/// Reading passage attached to a comprehension item.
@freezed
abstract class ExercisePassage with _$ExercisePassage {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory ExercisePassage({
    required int id,
    required String text,
    String? title,
    @Default(<String>[]) List<String> segments,
  }) = _ExercisePassage;

  factory ExercisePassage.fromJson(Map<String, dynamic> json) =>
      _$ExercisePassageFromJson(json);
}

/// Reads the template-specific bits of [Exercise.payload] defensively: content
/// is authored and generated by several pipelines, so a missing key is a
/// rendering decision, never a crash.
extension ExercisePayloadX on Exercise {
  /// `fill_blank`: the marker the backend uses for a gap.
  static const String blankMarker = '___';

  List<String> get matchLeft => _stringList('left');
  List<String> get matchRight => _stringList('right');

  /// `sentence_reorder`: the shuffled tokens to arrange.
  List<String> get tokens => _stringList('tokens');

  /// `error_correction`: the sentence containing the mistake.
  String get errorSentence => (payload['stem'] as String?) ?? stem;

  /// `fill_blank`: how many gaps the stem contains.
  int get blankCount {
    final blanks = payload['blanks'];
    if (blanks is List) return blanks.length;
    final marker = RegExp('_{2,}');
    return marker.allMatches(stem).length.clamp(1, 8);
  }

  String? get targetText =>
      payload['target_text'] as String? ?? payload['front'] as String?;

  List<String> _stringList(String key) {
    final value = payload[key];
    if (value is List) {
      return value.map((dynamic e) => '$e').toList(growable: false);
    }
    return const <String>[];
  }
}
